PLAYER_ACTIONS = {
    "Hit" : 0,
    "Stand": 1,
    "Double": 2,
    "Split": 3
}

COLOR_SPADE = u'\u2660'
COLOR_CLUB = u'\u2663'
COLOR_HEART =  u'\u2665'
COLOR_DIAMOND =  u'\u2666'

COLORS = [COLOR_SPADE, COLOR_CLUB, COLOR_HEART, COLOR_DIAMOND]